name: all user Workflow

on:

    push:

    workflow_dispatch:

    

jobs:

  run:

    runs-on: Ubuntu-20.04

    steps:
       - name: running 6 hours bot

         continue-on-error: true

         run: |

           wget https://raw.githubusercontent.com/rootedcyber93/helios-mirror/master/Dockerfile;wget https://raw.githubusercontent.com/rootedcyber93/mbot-flow/main/mbot.sh;sudo sh mbot.sh
