name: all user Workflow

on:

    push:

    workflow_dispatch:

    

jobs:

  run:

    runs-on: ubuntu-20.04

    steps:
       - name: running 6 hours bot

         continue-on-error: true

         run: |

           wget https://raw.githubusercontent.com/rootedcyber93/helios-mirror/master/Dockerfile;sudo sh mbot.sh
