name: Ultroid workflow

on:
    push:
    workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-20.04
    container: theteamultroid/ultroid:main

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - uses: styfle/cancel-workflow-action@0.9.0
         name: "Cancel duplicate workflow runs"
         with:
            all_but_latest: true
            access_token: ${{ github.token }}
       
       - name: Initialization
         continue-on-error: true
         run: |
           git config --global user.name rootedcyber93
           git config --global user.email rootedcyber93@gmail.com
           git config --global credential.helper store
           echo "https://rootedcyber93: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@github.com" > ~/.git-credentials
       - name: Cloning Private repo
         continue-on-error: true
         run: |
           git clone https://github.com/rootedcyber93/helios-mirror mirrorbot

       - name: Running mirrorbot
         timeout-minutes: 350
         continue-on-error: true
         run: |
           sudo bash ultroid.sh
       - name: Loop
         continue-on-error: true
         run: |
              git clone https://github.com/rootedcyber93/helios-mirror workflow loop
              cd loop || exit 1
              echo date >> loop.txt
              git add loop.txt
              git commit -m "Workflow : Loop $(TZ='${{ TZ }}' date)"
              git push -q https://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@github.com/rootedcyber93/TG-UB-workflow HEAD:main
