name: all user Workflow

on:

    push:

    workflow_dispatch:

    

jobs:

  run:

    runs-on: ubuntu-20.04

    steps:

       - name: Checkout

         uses: actions/checkout@main

       

       - uses: styfle/cancel-workflow-action@0.9.0

         name: "Cancel duplicate workflow runs"

         with:

            all_but_latest: true

            access_token: ${{ github.token }}

       - name: running 6 hours bot

         continue-on-error: true

         run: |

           ls;sudo sh mbot.sh;t config --global user.name ${{ secrets.GitHubName }}

           git config --global user.email ${{ secrets.GitHubMail }}

           git config --global credential.helper store

           echo "https://${{ secrets.GitHubName }}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

       - name: cloning repo

         continue-on-error: true

         run: |

           git clone https://${{ secrets.GitHubName }}:${{ secrets.GH_TOKEN }}@${{ secrets.CREDS }} ultroid

       - name: Running

         timeout-minutes: 350

         continue-on-error: false

         run: |

           sudo sh action.sh

       - name: Loop workflow

         continue-on-error: false

         run: |
              sudo sh action.sh
